[2020-05-13 23:05:32,188] INFO [GroupCoordinator 0]: Preparing to rebalance group console-consumer-89946 in state PreparingRebalance with old generation 0 (__consumer_offsets-7) (reason: Adding new member consumer-console-consumer-89946-1-7830bcdf-4440-4402-9e08-9bcd3de153ad with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2020-05-13 23:05:32,189] INFO [GroupCoordinator 0]: Stabilized group console-consumer-89946 generation 1 (__consumer_offsets-7) (kafka.coordinator.group.GroupCoordinator)
[2020-05-13 23:05:32,193] INFO [GroupCoordinator 0]: Assignment received from leader for group console-consumer-89946 for generation 1 (kafka.coordinator.group.GroupCoordinator)
[2020-05-13 23:06:02,957] INFO Terminating process due to signal SIGHUP (org.apache.kafka.common.utils.LoggingSignalHandler)
[2020-05-13 23:06:02,978] INFO [KafkaServer id=0] shutting down (kafka.server.KafkaServer)
[2020-05-13 23:06:02,989] INFO [KafkaServer id=0] Starting controlled shutdown (kafka.server.KafkaServer)
[2020-05-13 23:06:02,990] INFO [GroupCoordinator 0]: Member[group.instance.id None, member.id consumer-console-consumer-89946-1-7830bcdf-4440-4402-9e08-9bcd3de153ad] in group console-consumer-89946 has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2020-05-13 23:06:02,990] INFO [GroupCoordinator 0]: Preparing to rebalance group console-consumer-89946 in state PreparingRebalance with old generation 1 (__consumer_offsets-7) (reason: removing member consumer-console-consumer-89946-1-7830bcdf-4440-4402-9e08-9bcd3de153ad on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2020-05-13 23:06:02,990] INFO [GroupCoordinator 0]: Group console-consumer-89946 with generation 2 is now empty (__consumer_offsets-7) (kafka.coordinator.group.GroupCoordinator)
[2020-05-13 23:06:03,298] WARN Session 0x100003f43fa0000 for server localhost/127.0.0.1:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:75)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:363)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1223)
[2020-05-13 23:06:03,403] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2020-05-13 23:06:03,404] INFO [ZooKeeperClient Kafka server] Connected. (kafka.zookeeper.ZooKeeperClient)
[2020-05-13 23:06:04,483] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-05-13 23:06:04,484] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-05-13 23:06:04,584] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2020-05-13 23:06:06,507] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-05-13 23:06:06,507] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-05-13 23:06:07,877] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-05-13 23:06:07,877] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
